version: '3'
services:
  mongodb:
    container_name: mongodbreplicaset
    image: mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all"]
    expose:
     - "27017"
    ports:
     - "27017:27017"
    networks:
      - default
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodbreplicaset:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
  mongoexpress:
    container_name: mongoexpressreplicaset
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodbreplicaset
      ME_CONFIG_MONGODB_URL: mongodb://mongodbreplicaset:27017/?replicaSet=rs0
    depends_on:
      mongodb:
        condition: service_healthy
